tokenizer_type: hf
tokenizer_path: ('meta-llama/Llama-2-7b-chat-hf',)
pad_id: -1
vocab_size: -1
IRM_layers: [0]
loss_function_index: 0
default_root_dir: /home/huang717/DRAGN/IRM/injectable-alignment-model/runs/final_chat_shakespeare_layer_0_training/
checkpoint_path: /home/huang717/DRAGN/IRM/injectable-alignment-model/default_checkpoints/Llama-2-7b-chat-hf.ckpt
dataset_dir: /home/huang717/DRAGN/IRM/injectable-alignment-model/datasets/TinyShakespeare/
dataset_name: tiny_shakespeare
accelerator: gpu
num_nodes: 1
num_workers: 1
devices: 8
use_slurm: true
log_every_n_steps: 200
check_val_every_n_epoch: 1
val_check_interval: 0.25
batch_size: 8
gradient_accumulation_steps: 4
num_epochs: 10
lr: 0.00005
gamma: 0.85
seed: 42
early_stopping: 3
save_top_k: 5
save_predictions_during_training: true
regularize_loss: False
max_gen_len: 256
do_logging: False
experiment_name: Llama-2-7b-chat-hf_tiny_shakespeare.txt_31_training
from_pretrained: true
model_name: meta-llama/Llama-2-7b-chat-hf

model_config:
  attention_bias: false
  attention_dropout: 0.0
  bos_token_id: 1
  eos_token_id: 2
  hidden_act: silu
  hidden_size: 4096
  initializer_range: 0.02
  # intermediate_size: 11008
  max_position_embeddings: 4096
  model_type: llama
  num_attention_heads: 32
  num_hidden_layers: 32
  num_key_value_heads: 32
  pretraining_tp: 1
  rms_norm_eps: .00001
  rope_scaling: ~
  rope_theta: 10000.0
  tie_word_embeddings: false
  torch_dtype: float16
  transformers_version: 4.38.2
  use_cache: true
  vocab_size: 32000
  irm_layer_size: 1024 # set to -1 to use the "size_modifier" in IRM() class
  irm_layer_num: 4 # equals to the number of nn.Linear(). The number of nn.ReLU() is (irm_layer_num - 1).
